title: Data Toys
author: Anders Schneiderman
email: your-email@domain.com
description: Experiments applying Makers All Framework to making working with data more playful for non-geeks

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  - name: 'Gameboards as Dashboards'
    link: 'dashboard-gameboard/'
  - name: FAQ
    link: 'faq/'
  - name: Makers All
    link: 'https://makersall.org/'

